// Entertainment IP Leads Dataset (44 Curated Properties for Doha, Qatar)
const INITIAL_IPS = [
  {
    "id": "IP-001",
    "title": "CoComelon: Sing-A-Long Live!",
    "category": "Touring Stage Musical / Preschool Live Show",
    "licensor": "Moonbug Entertainment (Candle Media)",
    "producer": "Round Room Live",
    "person": "Stephen Shaw (Co-President) / Jonathan Shank (CEO)",
    "website": "https://roundroomlive.com",
    "email": "info@roundroomlive.com / booking@roundroomlive.com",
    "social": "linkedin.com/company/round-room-live | @roundroomlive",
    "past_shows": "80+ city North American theater tour (2024-2025), UK arena runs, Australia",
    "venue_fit": "QNCC Theater (2,300 seats) or Katara Opera House; prime preschool demographic",
    "status": "Not Contacted",
    "email_template": "Subject: Host Partnership Inquiry: Bringing CoComelon Live to Doha, Qatar (QNCC)\n\nDear Round Room Live Touring Team,\n\nI am reaching out regarding hosting and co-producing CoComelon: Sing-A-Long Live in Doha, Qatar. Our event production organization in Doha specializes in bringing world-class family IPs to the region. Given CoComelon's massive popularity across the GCC, we are exploring an exclusive performance run at the Qatar National Convention Centre (QNCC). We provide turnkey local staging, technical production, marketing, and venue management. Could we schedule a preliminary call to discuss touring availability, Middle East routing, and licensing terms?\n\nBest regards,",
    "notes": "Target Q1/Q2 school holiday run."
  },
  {
    "id": "IP-002",
    "title": "Bluey's Big Play",
    "category": "Theatrical Puppet Stage Show",
    "licensor": "BBC Studios",
    "producer": "Windmill Theatre Co / Andrew Kay & Cuffe & Taylor (for BBC Studios Live)",
    "person": "Natasha Spence (Head of Attractions, BBC Studios Live Entertainment)",
    "website": "https://www.bluey.tv/blueys-big-play/",
    "email": "live.entertainment@bbc.com / info@cuffeandtaylor.com",
    "social": "linkedin.com/company/bbc-studios | @officialblueytv",
    "past_shows": "Sydney Opera House, Madison Square Garden (NYC), Royal Festival Hall London, 65-city US tour",
    "venue_fit": "QNCC Auditorium; premier family theater production with massive cross-generational appeal",
    "status": "Not Contacted",
    "email_template": "Subject: Partnership Proposal: Hosting Bluey's Big Play in Doha, Qatar\n\nDear BBC Studios Live Entertainment Team,\n\nI am writing from Doha, Qatar, to explore hosting the international tour of Bluey's Big Play. We manage family entertainment productions in Doha and have the technical infrastructure and venue partnerships (including QNCC Theater) to support a multi-day theatrical residency. Bluey holds a dominant audience share in Qatar. We would welcome the opportunity to discuss technical riders, Middle East routing windows, and commercial terms.\n\nBest regards,",
    "notes": "High priority lead."
  },
  {
    "id": "IP-003",
    "title": "Hot Wheels Monster Trucks Live",
    "category": "Arena Motorsport & Stunt Entertainment",
    "licensor": "Mattel",
    "producer": "Family Entertainment Live",
    "person": "Ken Hudgens (CEO, Family Entertainment Live) / Julie Freeland (VP Global LBE, Mattel)",
    "website": "https://hotwheelsmonstertruckslive.com",
    "email": "info@familyentertainmentlive.com / booking@familyentertainmentlive.com",
    "social": "linkedin.com/company/family-entertainment-live | @hotwheelsmonstertruckslive",
    "past_shows": "Annual international arena tours across USA, Europe (London O2, Madrid), Australia",
    "venue_fit": "Lusail Multipurpose Arena or Ali Bin Hamad Al Attiya Arena (ABHA Arena)",
    "status": "Not Contacted",
    "email_template": "Subject: Arena Hosting Opportunity: Hot Wheels Monster Trucks Live in Doha, Qatar\n\nDear Family Entertainment Live Team,\n\nI am writing to inquire about international routing and hosting rights for Hot Wheels Monster Trucks Live in Doha, Qatar. With world-class indoor arena infrastructure such as Lusail Multipurpose Arena and ABHA Arena, Doha is primed to host high-octane family spectacles. Our entertainment operations team has extensive experience managing large-scale activations, venue logistics, and local promotions. We would love to connect with your international touring department to evaluate potential dates.\n\nBest regards,",
    "notes": "Requires indoor arena with dirt/floor protection capabilities."
  },
  {
    "id": "IP-004",
    "title": "Jurassic World: The Exhibition",
    "category": "Large-Scale Immersive Walk-Through Exhibition",
    "licensor": "Universal Destinations & Experiences",
    "producer": "NEON Global (formerly Cityneon)",
    "person": "Welby Altidor (Group Chief Creative Officer) / Ron Tan (CEO, NEON)",
    "website": "https://jurassicworldexhibition.com",
    "email": "info@neonglobal.com / inquiries@neonglobal.com",
    "social": "linkedin.com/company/neonglobal | @jurassicworldexhibition",
    "past_shows": "London ExCeL, Sydney, Toronto, Madrid, Seoul, Berlin (2,500 sqm; over 5M global visitors)",
    "venue_fit": "DECC (Doha Exhibition and Convention Centre) or QNCC Exhibition Halls; 2-3 month residency",
    "status": "Not Contacted",
    "email_template": "Subject: Venue & Co-Promotion Partnership: Jurassic World: The Exhibition in Doha\n\nDear NEON Global Touring Partnerships Team,\n\nI am reaching out regarding bringing Jurassic World: The Exhibition to Doha, Qatar. We coordinate event production and venue operations in Doha, working closely with DECC and QNCC. Given the region's strong appetite for blockbuster immersive experiences, a multi-month residency for Jurassic World represents a massive commercial opportunity. We would like to request an introductory discussion regarding minimum footprint specifications, licensing terms, and touring availability.\n\nBest regards,",
    "notes": "Requires 2,000-3,000 sqm pillar-free hall space."
  },
  {
    "id": "IP-005",
    "title": "Harry Potter: The Exhibition",
    "category": "Immersive Blockbuster Touring Exhibition",
    "licensor": "Warner Bros. Themed Entertainment",
    "producer": "Imagine Exhibitions & Semmel Exhibitions",
    "person": "Tom Zaller (CEO, Imagine Exhibitions) / Christoph Scholz (Director, Semmel)",
    "website": "https://harrypotterexhibition.com",
    "email": "info@imagineexhibitions.com / promoter@semmel.de",
    "social": "linkedin.com/company/imagine-exhibitions-inc | @harrypotterexhibition",
    "past_shows": "Paris Expo Porte de Versailles, Vienna, Philadelphia, Barcelona, Boston, Macau (1.5M+ visitors)",
    "venue_fit": "DECC or Katara Cultural Village; premier cultural-entertainment activation",
    "status": "Not Contacted",
    "email_template": "Subject: Host Venue Proposal: Harry Potter: The Exhibition in Doha, Qatar\n\nDear Imagine Exhibitions & Semmel Exhibitions Team,\n\nI am contacting you regarding host promoter partnerships for Harry Potter: The Exhibition in Doha, Qatar. Our team specializes in entertainment production, venue operations, and experiential activations in Qatar. We have strong connections with primary exhibition facilities such as DECC and QNCC, capable of accommodating your complete 20,000+ sq ft modular build. We would be pleased to review your local promoter requirements and discuss potential timeline windows.\n\nBest regards,",
    "notes": "Ideal for winter/spring tourism season."
  },
  {
    "id": "IP-006",
    "title": "Monopoly Lifesized",
    "category": "Interactive FEC / Immersive Role-Playing Experience",
    "licensor": "Hasbro",
    "producer": "The Path Entertainment Group",
    "person": "David Hutchinson (CEO, Path Entertainment Group) / Matt Proulx (VP LBE, Hasbro)",
    "website": "https://monopolylifesized.com",
    "email": "info@pathentertainment.com / licensing@pathentertainment.com",
    "social": "linkedin.com/company/the-path-entertainment-group | @monopolylifesized",
    "past_shows": "London flagship (Tottenham Court Rd), Riyadh Season (Boulevard City), Melbourne",
    "venue_fit": "Place Vendôme, Mall of Qatar, or Msheireb Downtown; high dwell-time attraction",
    "status": "Not Contacted",
    "email_template": "Subject: Location-Based Entertainment Partnership: Monopoly Lifesized in Qatar\n\nDear Path Entertainment Group Team,\n\nI am writing to inquire about licensing and franchise deployment opportunities for Monopoly Lifesized in Doha, Qatar. Doha's premium retail destinations (such as Place Vendôme and Mall of Qatar) are actively seeking interactive, high-repeat-visit LBE formats. We operate event production and commercial entertainment projects in Qatar and would like to explore opening a pop-up or permanent residency. Please let us know how we can initiate a discussion with your international business development team.\n\nBest regards,",
    "notes": "High retail synergy and repeat visit potential."
  },
  {
    "id": "IP-007",
    "title": "Blippi: The Wonderful World Tour",
    "category": "Live Interactive Character Show",
    "licensor": "Moonbug Entertainment",
    "producer": "Round Room Live",
    "person": "Stephen Shaw (Round Room Live) / Moonbug Live Team",
    "website": "https://blippitour.com",
    "email": "booking@roundroomlive.com / press@moonbug.com",
    "social": "linkedin.com/company/moonbug-entertainment | @blippi",
    "past_shows": "100+ cities in North America, UK nationwide tour, UAE (Etihad Arena)",
    "venue_fit": "QNCC Auditorium or Katara Drama Theater; energetic edutainment show",
    "status": "Not Contacted",
    "email_template": "Subject: Touring Inquiry: Blippi Live Stage Show for Doha, Qatar\n\nDear Round Room Live Touring Directors,\n\nWe would like to discuss booking the Blippi live touring stage production for a performance series in Doha, Qatar. Our organization produces family and live entertainment events in Doha, providing end-to-end production support, local marketing, and venue liaison. Following the success of family IP shows in the region, Blippi is in very high demand among families across Qatar. Could you please share your upcoming Middle East routing schedule and standard venue/promoter package details?\n\nBest regards,",
    "notes": "Can be combined with CoComelon in a Moonbug festival package."
  },
  {
    "id": "IP-008",
    "title": "NERF Action Xperience (NERF AX)",
    "category": "Active Indoor FEC / Family Sports Entertainment",
    "licensor": "Hasbro Global Location Based Entertainment",
    "producer": "Kilburn Live / Kingsmen Creatives",
    "person": "Mark Manuel (CEO, Kilburn Live) / Matt Proulx (VP LBE, Hasbro)",
    "website": "https://nerfax.com",
    "email": "info@kilburnlive.com / lbe@hasbro.com",
    "social": "linkedin.com/company/kilburn-live | @nerfactionxperience",
    "past_shows": "Permanent & modular venues in Singapore, UK (Manchester), USA (New Jersey, Atlanta)",
    "venue_fit": "Doha Festival City, Aspire Zone, or Mall of Qatar; obstacle & arena play",
    "status": "Not Contacted",
    "email_template": "Subject: Expression of Interest: Developing a NERF Action Xperience in Qatar\n\nDear Kilburn Live & Hasbro LBE Team,\n\nI am reaching out regarding bringing the NERF Action Xperience format to Doha, Qatar, as a pop-up attraction or indoor FEC installation. With Qatar's immense focus on active lifestyles, sports entertainment, and state-of-the-art indoor leisure facilities, NERF AX aligns perfectly with local demand. We coordinate large-scale active entertainment zones and family attractions in Qatar and would welcome an exploratory discussion regarding regional franchise/hosting models.\n\nBest regards,",
    "notes": "Excellent match for indoor active/inflatable entertainment focus."
  },
  {
    "id": "IP-009",
    "title": "Peanuts (Snoopy & Charlie Brown) Discovery Village",
    "category": "Themed Edutainment, Pop-Up Cafe & Exhibition",
    "licensor": "WildBrain CPLG",
    "producer": "WildBrain CPLG Live & Experiential",
    "person": "Maarten Weck (EVP & Managing Director, WildBrain CPLG) / Evi Pandouvani (VP EMEA Licensing)",
    "website": "https://www.wildbrain.com",
    "email": "info@cplg.com / licensing@wildbrain.com",
    "social": "linkedin.com/company/wildbrain-cplg | @snoopygrams",
    "past_shows": "Asia Pacific touring exhibitions, Singapore Changi Airport Snow & Play Zone, European pop-ups",
    "venue_fit": "Qatar National Library, Katara, or luxury mall atriums; wholesome, educational",
    "status": "Not Contacted",
    "email_template": "Subject: Collaboration Opportunity: Peanuts / Snoopy Activation in Doha, Qatar\n\nDear WildBrain CPLG Licensing Team,\n\nI am writing to express our interest in developing an official Peanuts (Snoopy) experiential activation, pop-up village, or touring exhibition in Doha, Qatar. Our team specializes in visual communications, thematic builds, and event production across Doha's premier civic and retail venues. We believe a bespoke Peanuts edutainment experience would resonate strongly during Qatar's peak winter events season. Could we schedule an introduction with your Middle East LBE team to review concepts and licensing frameworks?\n\nBest regards,",
    "notes": "Dedicated Middle East representation office available."
  },
  {
    "id": "IP-010",
    "title": "PAW Patrol Live! ('Race to the Rescue')",
    "category": "Large-Scale Theatrical Character Musical",
    "licensor": "Paramount Global Live Experiences / Nickelodeon",
    "producer": "VStar Entertainment Group / EventBox (MENA)",
    "person": "Jack Finch (Touring Director, VStar) / EventBox Booking Team",
    "website": "https://www.pawpatrollive.com",
    "email": "info@vstarentertainment.com / info@eventboxonline.com",
    "social": "linkedin.com/company/vstar-entertainment-group | @pawpatrollive",
    "past_shows": "Over 40 countries, 5.5M+ attendees; arena and theater dates in Dubai, KSA, London, USA",
    "venue_fit": "QNCC Theater; proven regional record",
    "status": "Not Contacted",
    "email_template": "Subject: Host Booking Inquiry: PAW Patrol Live! Season in Doha, Qatar\n\nDear VStar Entertainment & EventBox Teams,\n\nI am writing to inquire about routing availability and co-promotion terms for PAW Patrol Live! in Doha, Qatar. Having delivered premier brand activations in Qatar, our team is equipped to handle full local venue coordination, stage management at QNCC, and comprehensive ticketing/marketing campaigns. We are keen to evaluate potential run dates for the coming season. Please let us know your current touring schedule for the GCC and standard technical requirements.\n\nBest regards,",
    "notes": "Top performer across GCC markets."
  },
  {
    "id": "IP-011",
    "title": "Katmandu: Park & Media-Based Attractions",
    "category": "Turnkey Family Entertainment Center (FEC) & Interactive Dark Ride",
    "licensor": "Falcon's Beyond Global",
    "producer": "Falcon's Beyond Destinations",
    "person": "Cecil D. Magpuri (CEO) / Simon Philips (President)",
    "website": "https://falconsbeyond.com",
    "email": "info@falconsbeyond.com / bd@falconsbeyond.com",
    "social": "linkedin.com/company/falconsbeyond | @falconsbeyond",
    "past_shows": "Katmandu Park Punta Cana, Mallorca, Saudi Qiddiya attraction integrations",
    "venue_fit": "Indoor theme park anchor for commercial masterplans in Lusail or Al Maha Island",
    "status": "Not Contacted",
    "email_template": "Subject: LBE Partnership: Interactive Family Attractions for Qatar Projects\n\nDear Falcon's Beyond Business Development Team,\n\nI am reaching out regarding your experiential entertainment IP and attraction modules (such as Katmandu and proprietary media rides) for prospective integration into family entertainment developments in Qatar. We are based in Doha and work across event project management, spatial design, and entertainment activations. We see strong alignment for high-tech, immersive FEC modules in Qatar's rapidly expanding leisure ecosystem. I would love to connect with your GCC business development leads to explore potential collaboration.\n\nBest regards,",
    "notes": "Modular attraction systems available for custom spatial layout."
  },
  {
    "id": "IP-012",
    "title": "Marvel: Universe of Super Heroes / The Science of Pixar",
    "category": "Blockbuster Science & Pop-Culture Museum Touring Exhibition",
    "licensor": "Marvel / Disney / Pixar",
    "producer": "Semmel Exhibitions",
    "person": "Christoph Scholz (Director of Exhibitions, Semmel Concerts Entertainment)",
    "website": "https://www.semmel-exhibitions.com",
    "email": "contact@semmel-exhibitions.com / promoter@semmel.de",
    "social": "linkedin.com/company/semmel-concerts-entertainment-gmbh | @semmel_exhibitions",
    "past_shows": "Museum of Science Boston, Chicago MSI, Frankfurt, Madrid, Seoul; 1M+ visitors",
    "venue_fit": "DECC, Qatar Museums collaboration, or Katara; blends STEM education with pop culture",
    "status": "Not Contacted",
    "email_template": "Subject: Local Promoter Inquiry: Marvel / Pixar Touring Exhibitions in Doha\n\nDear Semmel Exhibitions Team,\n\nI am writing to inquire about promoter partnership terms for your premier touring exhibitions (specifically Marvel: Universe of Super Heroes or The Science of Pixar) in Doha, Qatar. Our team coordinates major event logistics and exhibition venues in Doha, including DECC. With Qatar's strong focus on world-class museum exhibitions and youth STEM engagement, these exhibitions would be landmark cultural attractions. Could you share your promoter information deck and regional routing plans for the Middle East?\n\nBest regards,",
    "notes": "Strong institutional and sponsorship backing potential."
  },
  {
    "id": "IP-013",
    "title": "Peppa Pig Live!",
    "category": "Touring Character Musical / Preschool Stage Show",
    "licensor": "Hasbro / Entertainment One (eOne)",
    "producer": "Fierylight Productions / Fiery Angel",
    "person": "Martin Flitton (Producer, Fierylight) / Matt Proulx (VP LBE, Hasbro)",
    "website": "https://peppapiglive.com",
    "email": "info@fierylight.co.uk / lbe@hasbro.com",
    "social": "linkedin.com/company/hasbro | @peppapig",
    "past_shows": "Over 15 years of continuous international touring across UK, USA, Australia, and Middle East (Dubai Opera, Abu Dhabi)",
    "venue_fit": "QNCC Auditorium or Katara Drama Theater; massive appeal for toddler & preschool demographic",
    "status": "Not Contacted",
    "email_template": "Subject: Touring Inquiry: Hosting Peppa Pig Live in Doha, Qatar (QNCC)\n\nDear Fierylight Productions & Hasbro Live Team,\n\nI am writing to explore host promoter opportunities for Peppa Pig Live in Doha, Qatar. Our event production and family entertainment organization in Doha manages premier family theatrical seasons. With Peppa Pig's unmatched household brand recognition in the GCC, an exclusive multi-show weekend run at the Qatar National Convention Centre (QNCC) would draw substantial family attendance. We provide complete local staging, promoter marketing, and logistics. Could we discuss your Middle East routing availability and technical riders?\n\nBest regards,",
    "notes": "High repeat-viewing value; ideal for Eid or winter holiday programming."
  },
  {
    "id": "IP-014",
    "title": "Minecraft Experience: Villager Rescue",
    "category": "Large-Scale Interactive Immersive Walk-Through Experience",
    "licensor": "Mojang Studios / Microsoft",
    "producer": "Experience MOD / Supply + Demand",
    "person": "Olivier Goulet (President, Supply + Demand) / Kayleen Walters (Head of Franchise, Mojang)",
    "website": "https://www.minecraftexperience.com",
    "email": "contact@supply-demand.ca / partner@minecraftexperience.com",
    "social": "linkedin.com/company/supply-demand | @minecraftexperience",
    "past_shows": "World premiere in Dallas (2024), international tours in Singapore (2025/2026), Mexico City, and London",
    "venue_fit": "DECC (Doha Exhibition and Convention Centre) or QNCC Halls; requires 15,000–20,000 sq ft hall space",
    "status": "Not Contacted",
    "email_template": "Subject: Host Venue Partnership: Bringing Minecraft Experience to Doha, Qatar\n\nDear Experience MOD & Supply + Demand Teams,\n\nI am reaching out regarding hosting the Minecraft Experience: Villager Rescue in Doha, Qatar. As one of the world's most popular gaming franchises, Minecraft has a massive youth and family following across the GCC. Our event coordination team operates major exhibition residencies in Doha, working closely with DECC and QNCC. We would welcome the opportunity to discuss hosting parameters, minimum spatial requirements, and Middle East tour routing for 2026/2027.\n\nBest regards,",
    "notes": "Top gaming IP; immense appeal for ages 6-16 and families."
  },
  {
    "id": "IP-015",
    "title": "Disney On Ice",
    "category": "Large-Scale Arena Ice Skating Spectacle",
    "licensor": "The Walt Disney Company",
    "producer": "Feld Entertainment",
    "person": "Kenneth Feld (Chairman & CEO) / Juliette Feld Grossman (COO) / Jeff Meyer (VP Global Tour Booking)",
    "website": "https://www.disneyonice.com",
    "email": "tourbooking@feldinc.com / international@feldinc.com",
    "social": "linkedin.com/company/feld-entertainment | @disneyonice",
    "past_shows": "Annual worldwide arena tours across 75+ countries, including Etihad Arena (Abu Dhabi) and Coca-Cola Arena (Dubai)",
    "venue_fit": "Lusail Multipurpose Arena or Ali Bin Hamad Al Attiya Arena; requires indoor Olympic ice pad installation",
    "status": "Not Contacted",
    "email_template": "Subject: Arena Routing Proposal: Disney On Ice in Doha, Qatar\n\nDear Feld Entertainment Global Touring Team,\n\nI am writing from Doha, Qatar, to discuss potential routing dates for Disney On Ice at our premier indoor venues, including Lusail Multipurpose Arena and ABHA Arena. Our team has extensive experience facilitating arena transformations, ice-floor chilling installations, and local ticketing campaigns in Qatar. Given the enormous appetite for Disney experiences in Doha, an arena engagement represents a proven high-yield production. Please let us know your international booking timeline and promoter specifications.\n\nBest regards,",
    "notes": "Requires 7-10 days ice install & rehearsals."
  },
  {
    "id": "IP-016",
    "title": "World of Barbie",
    "category": "Immersive Pop-Up Exhibition & Thematic Walk-Through",
    "licensor": "Mattel",
    "producer": "Kilburn Live",
    "person": "Mark Manuel (CEO, Kilburn Live) / Julie Freeland (VP Global LBE, Mattel)",
    "website": "https://theworldofbarbie.com",
    "email": "info@kilburnlive.com / partnerships@theworldofbarbie.com",
    "social": "linkedin.com/company/kilburn-live | @worldofbarbietour",
    "past_shows": "Toronto, Los Angeles (Santa Monica Place), Dallas; 20,000 sq ft immersive Dreamhouse buildout",
    "venue_fit": "Place Vendôme, Mall of Qatar luxury court, or DECC; high lifestyle appeal and Instagrammable photo moments",
    "status": "Not Contacted",
    "email_template": "Subject: Experiential Partnership: World of Barbie Pop-Up in Doha, Qatar\n\nDear Kilburn Live & Mattel LBE Partnerships Team,\n\nI am contacting you regarding host promoter and venue opportunities for World of Barbie in Doha, Qatar. Doha is home to some of the world's most luxurious retail destinations (including Place Vendôme and Mall of Qatar) that actively invest in blockbuster experiential pop-ups. We manage spatial installations and event productions in Qatar and would like to explore opening a multi-month Dreamhouse residency. Could we connect to review footprint specs and licensing criteria?\n\nBest regards,",
    "notes": "High retail synergy and female/family demographic draw."
  },
  {
    "id": "IP-017",
    "title": "Monster Jam",
    "category": "Arena Monster Truck Motorsport & Freestyle Stunt Event",
    "licensor": "Feld Entertainment",
    "producer": "Feld Entertainment",
    "person": "Bill Easterly (VP of Operations, Monster Jam) / Jeff Meyer (VP Global Booking)",
    "website": "https://www.monsterjam.com",
    "email": "international@feldinc.com / booking@monsterjam.com",
    "social": "linkedin.com/company/feld-entertainment | @monsterjam",
    "past_shows": "International stadium and arena tours across North America, Europe, Australia, and Riyadh (Kingdom Arena)",
    "venue_fit": "Lusail Stadium or Lusail Multipurpose Arena / Al Thumama outdoor concourse; requires dirt transport & exhaust ventilation",
    "status": "Not Contacted",
    "email_template": "Subject: Arena / Stadium Hosting: Monster Jam Tour Dates in Qatar\n\nDear Monster Jam International Touring Team,\n\nI am writing to explore host promoter cooperation for bringing Monster Jam to Doha, Qatar. Qatar boasts premier stadium and arena venues with full heavy-logistics access, including Lusail Multipurpose Arena and outdoor stadium precincts. Our event team specializes in large-scale technical activations and municipal permitting in Doha. We would welcome the opportunity to discuss dirt floor logistics, technical riders, and touring windows for a Qatar weekend spectacle.\n\nBest regards,",
    "notes": "High male youth & family ticket velocity."
  },
  {
    "id": "IP-018",
    "title": "The FRIENDS Experience: The One in Doha",
    "category": "Immersive Pop-Up Exhibition & Iconic TV Set Re-creations",
    "licensor": "Warner Bros. Discovery Global Themed Entertainment",
    "producer": "Original X Productions (OGX) / RWS Global",
    "person": "Stacy Moscatelli (CEO, OGX Productions) / Peter van Roden (SVP, Warner Bros.)",
    "website": "https://friendstheexperience.com",
    "email": "info@ogxproductions.com / partnerships@friendstheexperience.com",
    "social": "linkedin.com/company/ogx-productions | @friendstheexperience",
    "past_shows": "Flagship in NYC, touring runs in London (ExCeL), Paris, Brussels, Boston, Melbourne",
    "venue_fit": "Katara Cultural Village, Msheireb Downtown Doha, or DECC; appeals to young adults, expats, and tourists",
    "status": "Not Contacted",
    "email_template": "Subject: Venue Collaboration: The FRIENDS Experience Residency in Doha\n\nDear OGX Productions & Warner Bros. Themed Entertainment Teams,\n\nI am reaching out to propose a host partnership for bringing The FRIENDS Experience to Doha, Qatar. With a cosmopolitan expat population and high retail leisure dwell-times in locations like Msheireb Downtown and Katara, an interactive set re-creation featuring Central Perk and interactive photo moments would be a major seasonal draw. We provide turnkey event logistics, venue coordination, and local operations in Doha. Let us know if we can schedule an introductory discussion.\n\nBest regards,",
    "notes": "Excellent coffee shop / merchandise revenue generator."
  },
  {
    "id": "IP-019",
    "title": "Transformers: The Experience",
    "category": "Immersive Walk-Through Animatronics & Sci-Fi Exhibition",
    "licensor": "Hasbro",
    "producer": "NEON Global (formerly Cityneon)",
    "person": "Welby Altidor (CCO, NEON) / Matt Proulx (VP Global LBE, Hasbro)",
    "website": "https://www.neonglobal.com",
    "email": "info@neonglobal.com / inquiries@neonglobal.com",
    "social": "linkedin.com/company/neonglobal | @transformersofficial",
    "past_shows": "Global tour stops in North America and China, featuring life-sized Autobots, interactive consoles, and AR missions",
    "venue_fit": "DECC or QNCC Exhibition Halls; requires high-ceiling hall for life-sized Optimus Prime and Bumblebee figures",
    "status": "Not Contacted",
    "email_template": "Subject: Host Promoter Inquiry: Transformers: The Experience in Doha\n\nDear NEON Global Touring Team,\n\nI am writing regarding bringing Transformers: The Experience to Doha, Qatar. Following the immense regional interest in science-fiction and interactive entertainment, a multi-month Transformers exhibition at the Doha Exhibition and Convention Centre (DECC) offers immense promotional synergy. Our team manages full local production, venue leasing, and marketing in Doha. We would be delighted to review spatial specifications, shipping timelines, and commercial licensing terms.\n\nBest regards,",
    "notes": "Requires 8m+ vertical clearance for scale animatronics."
  },
  {
    "id": "IP-020",
    "title": "L.O.L. Surprise! Live: Calling All B.B.s",
    "category": "Live Hologram & Multi-Media Character Concert",
    "licensor": "MGA Entertainment",
    "producer": "Terrapin Station Entertainment",
    "person": "Jonathan Shank (Producer, Terrapin Station Entertainment) / Isaac Larian (CEO, MGA)",
    "website": "https://lolsurpriselive.com",
    "email": "info@terrapinent.com / booking@terrapinent.com",
    "social": "linkedin.com/company/terrapin-station-entertainment | @lolsurprise",
    "past_shows": "44-city North American tour, UK arena & theater dates with life-size characters, holograms, and LED visuals",
    "venue_fit": "QNCC Theater or Lusail Arena; vibrant high-fashion kids pop concert format",
    "status": "Not Contacted",
    "email_template": "Subject: Tour Booking Inquiry: L.O.L. Surprise! Live in Doha, Qatar\n\nDear Terrapin Station Entertainment & MGA Live Team,\n\nI am contacting you regarding booking the L.O.L. Surprise! Live production for performances in Doha, Qatar. L.O.L. Surprise! has a massive retail and fan presence across Qatar's toy and lifestyle sectors. Our event production company in Doha delivers turnkey theatrical staging, ticketing promotion, and venue management at premier venues like QNCC Theater. Could you provide details on international touring availability and promoter requirements for the Middle East?\n\nBest regards,",
    "notes": "Top performer for young girls & family demographic."
  },
  {
    "id": "IP-021",
    "title": "Sesame Street Live!",
    "category": "Theatrical Stage Musical / Edutainment Show",
    "licensor": "Sesame Workshop",
    "producer": "Round Room Live",
    "person": "Stephen Shaw (Co-President, Round Room Live) / Whit Higgins (EVP Sesame Workshop)",
    "website": "https://sesamestreetlive.com",
    "email": "booking@roundroomlive.com / licensing@sesame.org",
    "social": "linkedin.com/company/round-room-live | @sesamestreet",
    "past_shows": "Multi-decade global touring legacy across North American and international theaters and civic centers",
    "venue_fit": "QNCC Theater or Katara Opera House; universally trusted educational brand",
    "status": "Not Contacted",
    "email_template": "Subject: Theatrical Partnership: Hosting Sesame Street Live in Doha, Qatar\n\nDear Round Room Live Touring Team,\n\nI am writing to inquire about international touring dates for Sesame Street Live in Doha, Qatar. With Sesame Street's long-standing cultural stature and educational values, a live theatrical staging in Doha at the Qatar National Convention Centre (QNCC) would be warmly received by schools, families, and community institutions. We provide comprehensive local production support and venue coordination. Let us know who we can connect with to discuss booking and routing options.\n\nBest regards,",
    "notes": "Strong potential for morning school matinees and family weekend shows."
  },
  {
    "id": "IP-022",
    "title": "The Smurfs Live on Stage & Smurfs Play Park",
    "category": "Theatrical Musical & Turnkey Inflatable / FEC Modular Play Park",
    "licensor": "IMPS / Lafig Belgium",
    "producer": "EventBox / Nick Grace Management",
    "person": "Fabienne Gilles (CCO, IMPS) / EventBox Middle East Booking Team",
    "website": "https://www.smurfbusiness.com",
    "email": "licensing@smurf.com / info@eventboxonline.com",
    "social": "linkedin.com/company/eventbox | @smurfs.official",
    "past_shows": "Touring stage shows across Asia, Europe, and GCC (Dubai, Bahrain); inflatable Smurfs village pop-ups",
    "venue_fit": "Mall of Qatar Atrium, Doha Festival City, or QNCC; versatile for stage show or active play park",
    "status": "Not Contacted",
    "email_template": "Subject: Event Partnership: The Smurfs Live Show & Activation in Doha\n\nDear EventBox & IMPS Licensing Teams,\n\nI am reaching out regarding hosting The Smurfs Live Show or an interactive Smurfs village/play park activation in Doha, Qatar. Our Doha-based event operations group has extensive experience executing family activations and branded entertainment inside Qatar's premier shopping centers and civic event spaces. The Smurfs hold enduring family appeal across the GCC. We would like to explore licensing parameters and touring packages for the upcoming season.\n\nBest regards,",
    "notes": "Modular inflatable and stage assets adapt to mall or outdoor festival spaces."
  },
  {
    "id": "IP-023",
    "title": "Disney Jr. Live On Tour: Let's Play! (feat. Spidey)",
    "category": "Touring Theatrical Musical & Character Concert",
    "licensor": "Disney Branded Television / Marvel",
    "producer": "Terrapin Station Entertainment",
    "person": "Jonathan Shank (Producer & CEO, Terrapin Station)",
    "website": "https://www.disneyjuniortour.com",
    "email": "booking@terrapinent.com / info@terrapinent.com",
    "social": "linkedin.com/company/terrapin-station-entertainment | @disneyjunior",
    "past_shows": "60+ city North American tour (2024-2025), UK arena and theater debut (2025/2026), Pollstar-nominated family tour",
    "venue_fit": "QNCC Theater (2,300 seats); high-octane musical featuring Spidey and Disney Jr favorites with huge preschool draw",
    "status": "Not Contacted",
    "email_template": "Subject: Tour Booking Inquiry: Disney Jr. Live (Let's Play!) in Doha, Qatar\n\nDear Terrapin Station Entertainment Touring Team,\n\nI am writing to explore host promoter booking opportunities for bringing Disney Jr. Live On Tour: Let's Play! to Doha, Qatar. Our event production company in Doha manages premier theatrical and family entertainment seasons at world-class venues like the Qatar National Convention Centre (QNCC) Theater. With Marvel's Spidey and Disney Junior ranking among the most-watched preschool franchises across Qatar and the GCC, a multi-performance weekend run would be an exceptional commercial success. We provide turnkey local staging, technical coordination, marketing, and municipal approvals. Could you share your upcoming international routing schedule and promoter package details?\n\nBest regards,",
    "notes": "Ideal for winter/spring holiday programming."
  },
  {
    "id": "IP-024",
    "title": "BBC Earth Experience (Narrated by David Attenborough)",
    "category": "360-Degree Multi-Screen Immersive Natural History Experience",
    "licensor": "BBC Studios",
    "producer": "Moon Eye Productions / Live Nation",
    "person": "Frederik van Alkemade (CEO, Moon Eye Productions) / Natasha Spence (Head of Attractions, BBC Studios)",
    "website": "https://bbcearthexperience.com",
    "email": "info@mooneyeproductions.com / live.entertainment@bbc.com",
    "social": "linkedin.com/company/bbc-studios | @bbcearth",
    "past_shows": "The Daikin Centre London (over 350,000 visitors), Melbourne Convention and Exhibition Centre (Australia)",
    "venue_fit": "DECC (Doha Exhibition and Convention Centre) or QNCC Exhibition Halls; multi-projector modular spatial pavilion",
    "status": "Not Contacted",
    "email_template": "Subject: Venue Partnership Inquiry: BBC Earth Experience in Doha, Qatar\n\nDear Moon Eye Productions & BBC Studios Live Teams,\n\nI am reaching out regarding hosting the BBC Earth Experience in Doha, Qatar. As Qatar continues to prioritize world-class educational and cultural entertainment, this landmark multi-screen natural history experience narrated by Sir David Attenborough aligns seamlessly with national cultural tourism objectives. Our team coordinates venue operations and logistics in Doha, with strong ties to premier exhibition spaces like DECC. We would welcome an introductory meeting to discuss spatial requirements, licensing terms, and potential residency dates for 2026/2027.\n\nBest regards,",
    "notes": "Substantial school group and educational excursion potential."
  },
  {
    "id": "IP-025",
    "title": "The Very Hungry Caterpillar Show",
    "category": "Award-Winning Theatrical Puppet Show",
    "licensor": "World of Eric Carle / Penguin Random House",
    "producer": "Rockefeller Productions",
    "person": "Jonathan Rockefeller (Creator & Director, Rockefeller Productions)",
    "website": "https://hungrycaterpillarshow.com",
    "email": "info@rockefellerproductions.com / booking@hungrycaterpillarshow.com",
    "social": "linkedin.com/company/rockefeller-productions | @hungrycaterpillarshow",
    "past_shows": "Longest-running Off-Broadway children's show; global tours across UK, Australia, New Zealand, Canada, and South Korea",
    "venue_fit": "Katara Drama Theater or QNCC Auditorium; intimate, high-artistry puppetry tailored for toddlers and early learners",
    "status": "Not Contacted",
    "email_template": "Subject: Theatrical Booking Inquiry: The Very Hungry Caterpillar Show in Doha\n\nDear Rockefeller Productions Booking Team,\n\nI am writing to inquire about international touring availability for The Very Hungry Caterpillar Show in Doha, Qatar. We produce curated family and performing arts events in Doha, collaborating with premier cultural spaces including Katara Cultural Village and QNCC. Eric Carle's timeless story is beloved by Qatar's multi-national families and international school networks. We would be delighted to discuss routing dates, technical riders, and co-promotion structures for a multi-day residency.\n\nBest regards,",
    "notes": "Compact cast and physical footprint; straightforward freight and setup."
  },
  {
    "id": "IP-026",
    "title": "Crayola IDEAworks: The Creativity Exhibition",
    "category": "Hands-On Interactive STEM/Art Touring Exhibition",
    "licensor": "Crayola LLC",
    "producer": "Imagine Exhibitions / Agency808",
    "person": "Tom Zaller (CEO, Imagine Exhibitions) / Warren Schorr (SVP Business Development, Crayola)",
    "website": "https://www.imagineexhibitions.com/crayola-ideaworks",
    "email": "info@imagineexhibitions.com / licensing@crayola.com",
    "social": "linkedin.com/company/imagine-exhibitions-inc | @crayola",
    "past_shows": "World premiere at The Franklin Institute (Philadelphia), Idaho Museum, science centers and convention halls across North America",
    "venue_fit": "DECC or Qatar National Library / Katara; 12,000–18,000 sq ft interactive RFID-tagged creative learning adventure",
    "status": "Not Contacted",
    "email_template": "Subject: Host Promoter Proposal: Crayola IDEAworks Exhibition in Doha, Qatar\n\nDear Imagine Exhibitions & Crayola LBE Teams,\n\nI am contacting you regarding bringing the Crayola IDEAworks: The Creativity Exhibition to Doha, Qatar. Our event management team specializes in large-scale experiential exhibitions and family activations in Doha, with comprehensive operational access to premier venues such as DECC. With Qatar's strong national emphasis on youth creative thinking and interactive education, Crayola IDEAworks represents an outstanding fit for a seasonal residency. Could we schedule a brief introductory call to review promoter deck details and touring availability?\n\nBest regards,",
    "notes": "High sponsor interest from local educational and telecom entities."
  },
  {
    "id": "IP-027",
    "title": "Shaun the Sheep: Championsheeps & Live Touring Experience",
    "category": "Active Family Sports Pop-Up & Theatrical Exhibition",
    "licensor": "Aardman Animations",
    "producer": "Aardman Live & Attractions",
    "person": "Ngaio Harding-Hill (Head of Attractions & Live Experiences, Aardman)",
    "website": "https://www.aardman.com",
    "email": "live@aardman.com / licensing@aardman.com",
    "social": "linkedin.com/company/aardman-animations | @shaunthesheep",
    "past_shows": "Touring exhibitions across Japan (Museum of Art 'Eki' Kyoto), UK farm/heritage partnerships, Melbourne, international live stage shows",
    "venue_fit": "Aspire Zone, Place Vendôme, or outdoor seasonal winter activations in Lusail; humorous physical challenges and games",
    "status": "Not Contacted",
    "email_template": "Subject: Expression of Interest: Shaun the Sheep Experiential Activation in Qatar\n\nDear Aardman Live & Attractions Team,\n\nI am reaching out regarding hosting a Shaun the Sheep live experience, Championsheeps active sports activation, or touring exhibition in Doha, Qatar. Our event production company specializes in family activations, physical play zones, and brand experiences across Doha. Shaun the Sheep enjoys strong recognition across generations in the region, and an interactive activation during Qatar's peak winter events season would be a major draw. Please let us know who we can connect with to review available formats and licensing parameters.\n\nBest regards,",
    "notes": "Highly adaptable between indoor malls and outdoor winter festivals."
  },
  {
    "id": "IP-028",
    "title": "Paddington In Concert",
    "category": "Film with Live Symphony Orchestra & Touring Theatrical",
    "licensor": "Studiocanal",
    "producer": "TEG Europe / Raymond Gubbay Limited",
    "person": "Toby Leighton-Pope (Managing Director, TEG Europe) / Jonathan Higgins (Producer)",
    "website": "https://www.tegeurope.com",
    "email": "info@tegeurope.com / contact@raymondgubbay.co.uk",
    "social": "linkedin.com/company/teg-europe | @paddingtonbear",
    "past_shows": "Royal Festival Hall London, Royal Highland Centre Edinburgh, nationwide UK concert hall tour, Sydney",
    "venue_fit": "Qatar National Convention Centre (QNCC) Auditorium or Katara Opera House (in collaboration with Qatar Philharmonic Orchestra)",
    "status": "Not Contacted",
    "email_template": "Subject: Film-in-Concert Booking Proposal: Paddington In Concert in Doha\n\nDear TEG Europe & Raymond Gubbay Touring Teams,\n\nI am writing to explore host promoter opportunities for staging Paddington In Concert in Doha, Qatar. Our event organization coordinates live entertainment and orchestral productions in Doha, utilizing premier venues such as the QNCC Auditorium and Katara Opera House. Combining the universally acclaimed Paddington film with a live symphonic performance provides an elegant, premium family experience that strongly aligns with Doha's cultural audience. We would love to discuss licensing, touring conductor/score packages, and prospective dates.\n\nBest regards,",
    "notes": "High synergy for collaboration with the Qatar Philharmonic Orchestra."
  },
  {
    "id": "IP-029",
    "title": "Dinos Alive: An Immersive Experience",
    "category": "360-Degree Animatronic Jurassic Exhibition & VR Journey",
    "licensor": "Exhibition Hub",
    "producer": "Exhibition Hub",
    "person": "Mario Iacampo (CEO & Creative Director, Exhibition Hub)",
    "website": "https://dinosaliveexhibit.com",
    "email": "info@exhibitionhub.com / partners@exhibitionhub.com",
    "social": "linkedin.com/company/exhibition-hub | @dinosaliveexhibit",
    "past_shows": "Over 250 international exhibitions produced; tours in Chicago, Los Angeles, Perth, Melbourne, Brussels, and Schenectady",
    "venue_fit": "DECC Exhibition Halls or Katara; features 80+ life-sized moving animatronics, triassic sea VR, and fossil dig zones",
    "status": "Not Contacted",
    "email_template": "Subject: Local Promoter Inquiry: Dinos Alive Immersive Experience in Doha\n\nDear Exhibition Hub Partnerships Team,\n\nI am writing to inquire about bringing Dinos Alive: An Immersive Experience to Doha, Qatar, as a multi-month host promoter engagement. Our event logistics and venue management team operates major exhibitions in Qatar, working closely with DECC. Dinosaur exhibitions consistently achieve record-breaking family and school attendance in the Gulf. We would be pleased to receive your promoter specifications, technical rider, and regional tour availability for 2026/2027.\n\nBest regards,",
    "notes": "Proven commercial model with strong merchandise and VR upsells."
  },
  {
    "id": "IP-030",
    "title": "Thomas & Friends: Exploration Station & Live Tour",
    "category": "Interactive Family Pop-Up & Theatrical Train Experience",
    "licensor": "Mattel",
    "producer": "Rail Events Inc. / Mattel Global LBE",
    "person": "Julie Freeland (VP Global LBE, Mattel) / Matthew Stemmler (VP Operations, Rail Events)",
    "website": "https://www.railevents.com",
    "email": "info@railevents.com / lbe@mattel.com",
    "social": "linkedin.com/company/mattel | @thomasandfriends",
    "past_shows": "Decades-long 'Day Out With Thomas' heritage across 40+ historic railways and science centers in the US, UK, Canada, and Australia",
    "venue_fit": "Mall of Qatar, Doha Festival City, or Qatar Rail station activation; interactive railway play tables, character meet-and-greets, and mini electric train track rides",
    "status": "Not Contacted",
    "email_template": "Subject: Experiential Activation Inquiry: Thomas & Friends in Doha, Qatar\n\nDear Mattel LBE & Rail Events Teams,\n\nI am reaching out regarding hosting a Thomas & Friends interactive family activation, pop-up play park, or stage experience in Doha, Qatar. Our event production company has substantial experience delivering branded activations in partnership with leading commercial centers and transportation networks in Qatar. Thomas & Friends retains enormous emotional connection and brand loyalty with young families in the GCC. We would like to evaluate your modular touring attraction options and discuss potential hosting terms.\n\nBest regards,",
    "notes": "High potential for brand collaboration with local rail/transit infrastructure."
  },
  {
    "id": "IP-031",
    "title": "Cirque du Soleil: OVO / Corteo (Family Arena Touring)",
    "category": "Acrobatic Arena Spectacle & Family Theatrical Performance",
    "licensor": "Cirque du Soleil Entertainment Group",
    "producer": "Cirque du Soleil Entertainment Group",
    "person": "Stéphane Lefebvre (President & CEO) / Duncan Fisher (VP Touring Shows Division)",
    "website": "https://www.cirquedusoleil.com",
    "email": "booking@cirquedusoleil.com / corporate@cirquedusoleil.com",
    "social": "linkedin.com/company/cirque-du-soleil | @cirquedusoleil",
    "past_shows": "Toured over 100 cities in 20+ countries, arena dates at Coca-Cola Arena Dubai and Etihad Arena Abu Dhabi",
    "venue_fit": "Lusail Multipurpose Arena or Aspire Dome; massive international production with universal appeal across all demographics",
    "status": "Not Contacted",
    "email_template": "Subject: Arena Tour Booking Inquiry: Cirque du Soleil in Doha, Qatar\n\nDear Cirque du Soleil Touring & Booking Department,\n\nI am writing from Doha, Qatar, to explore hosting dates for your touring arena productions (such as OVO or Corteo). Qatar offers state-of-the-art indoor arena infrastructure including Lusail Multipurpose Arena, fully equipped to support the extensive aerial rigging, power, and logistics requirements of Cirque du Soleil. Our team specializes in large-scale event coordination and local promoter support in Doha. We would welcome a conversation regarding Middle East routing availability and promoter partnership arrangements.\n\nBest regards,",
    "notes": "Premium marquee event with high ticket yield across VIP and general tiers."
  },
  {
    "id": "IP-032",
    "title": "Angry Birds World: Live Pop-Up & Inflatable Adventure",
    "category": "Active Inflatable Fun Park, Obstacle Zone & Character Experience",
    "licensor": "Rovio Entertainment / SEGA",
    "producer": "Rovio Location-Based Entertainment / Trimoo",
    "person": "Katri Hyde (VP Brand Licensing, Rovio) / SEGA LBE Division",
    "website": "https://www.rovio.com",
    "email": "licensing@rovio.com / business@rovio.com",
    "social": "linkedin.com/company/rovio-entertainment-corporation | @angrybirdsofficial",
    "past_shows": "Permanent flagship indoor/outdoor park in Doha Festival City; international touring inflatable courses and pop-up carnivals across Europe and Asia",
    "venue_fit": "Al Maha Island, Lusail Winter Wonderland, or Mall Atriums; perfect for active inflatable outdoor activations or mall holiday pop-ups",
    "status": "Not Contacted",
    "email_template": "Subject: Experiential Collaboration: Angry Birds Touring Inflatable Adventure in Qatar\n\nDear Rovio LBE & Brand Partnerships Team,\n\nI am writing to discuss developing a seasonal Angry Birds touring pop-up, inflatable adventure park, or character activation in Qatar. With Angry Birds enjoying unmatched local familiarity through its existing presence in the country, a mobile, high-energy obstacle and inflatable challenge zone is ideally suited for Qatar's upcoming seasonal outdoor festivals. Our organization has deep expertise in managing inflatable event infrastructures, crowd safety, and venue operations. We would love to discuss licensing and touring package options.\n\nBest regards,",
    "notes": "Capitalizes on high existing brand recognition in the local market."
  },
  {
    "id": "IP-033",
    "title": "The Art of the Brick (Official LEGO® Art Touring Exhibition)",
    "category": "Blockbuster Contemporary Art & LEGO Touring Exhibition",
    "licensor": "The LEGO Group / Nathan Sawaya",
    "producer": "Exhibition Hub / Fever",
    "person": "Nathan Sawaya (Master Builder & Creator) / Mario Iacampo (CEO, Exhibition Hub)",
    "website": "https://theartofthebrickexpo.com",
    "email": "info@exhibitionhub.com / contact@brickartist.com",
    "social": "linkedin.com/company/exhibition-hub | @nathansawaya",
    "past_shows": "CNN Top 10 Global Must-See; toured 100+ cities in North America, Europe, Australia, and Asia (over 10M visitors)",
    "venue_fit": "DECC (Doha Exhibition and Convention Centre) or Katara Cultural Village; high cultural and family tourism appeal",
    "status": "Not Contacted",
    "email_template": "Subject: Host Promoter Inquiry: The Art of the Brick in Doha, Qatar\n\nDear Exhibition Hub & The Art of the Brick Teams,\n\nI am writing to explore host promoter cooperation for bringing The Art of the Brick (Nathan Sawaya) to Doha, Qatar. Our event management and production organization coordinates premier cultural and family exhibitions in Doha, working closely with leading venues including DECC and Katara. LEGO enjoys immense popularity across all demographics in Qatar, and an exhibition of this stature aligns with our national cultural tourism programming. We would welcome the opportunity to review your technical requirements, spatial layout, and touring windows for 2026/2027.\n\nBest regards,",
    "notes": "Globally acclaimed; high merchandise and family ticketing yield."
  },
  {
    "id": "IP-034",
    "title": "Brickman: Wonders of the World & Jurassic World LEGO® Adventure",
    "category": "Interactive LEGO® Touring Exhibition & Build Play Zones",
    "licensor": "The LEGO Group / Universal Brand Development",
    "producer": "The Brickman / Ryan McNaught",
    "person": "Ryan McNaught (LEGO Certified Professional & Director) / Mark Gray (General Manager)",
    "website": "https://www.thebrickman.com",
    "email": "exhibitions@thebrickman.com / info@thebrickman.com",
    "social": "linkedin.com/company/the-brickman | @brickmanexhibitions",
    "past_shows": "Over 8 globally touring exhibitions, including Paris Expo Porte de Versailles, Sydney, Melbourne, New Zealand (over 2M+ bricks per exhibition)",
    "venue_fit": "DECC, Place Vendôme, or Mall of Qatar; combines monumental LEGO builds with interactive guest building zones",
    "status": "Not Contacted",
    "email_template": "Subject: Venue & Promoter Proposal: Brickman LEGO Touring Exhibition in Doha\n\nDear The Brickman Touring & Exhibitions Team,\n\nI am reaching out regarding bringing a Brickman touring exhibition (such as Wonders of the World or Jurassic World by LEGO) to Doha, Qatar. We operate large-scale experiential and brand activations in Doha, with access to premier exhibition halls and luxury shopping destinations. Given the strong appetite for interactive, hands-on family experiences in the Gulf, a multi-month Brickman engagement would be a prime destination attraction. Please let us know your promoter package terms and upcoming Middle East touring availability.\n\nBest regards,",
    "notes": "Combines display sculptures with millions of loose bricks for guest build zones."
  },
  {
    "id": "IP-035",
    "title": "Masha and the Bear Live on Stage",
    "category": "Theatrical Character Musical & Puppet Show",
    "licensor": "Animaccord",
    "producer": "TEG Life Like Touring / EventBox (MENA)",
    "person": "Anton Valishin (Head of Live Events, Animaccord) / Anton Berezin (Producer, TEG)",
    "website": "https://masha-bear.com",
    "email": "info@animaccord.com / booking@lifeliketouring.com",
    "social": "linkedin.com/company/animaccord | @mashaandthebear",
    "past_shows": "Toured over 35 countries; sold-out runs in Dubai (Coca-Cola Arena), Italy, France, and Latin America",
    "venue_fit": "QNCC Theater (2,300 seats); immense preschool popularity across Arab and expat families in Doha",
    "status": "Not Contacted",
    "email_template": "Subject: Host Promoter Inquiry: Masha and the Bear Live in Doha, Qatar\n\nDear Animaccord & TEG Life Like Touring Teams,\n\nI am writing to explore host promoter opportunities for bringing Masha and the Bear Live on Stage to Doha, Qatar. Our event production company in Doha delivers turnkey family entertainment and theatrical seasons, working closely with the Qatar National Convention Centre (QNCC). Given Masha and the Bear's dominant viewership across the GCC, a multi-performance weekend run represents a guaranteed family draw. We provide full local technical staging, venue coordination, and comprehensive marketing. Could we discuss touring availability and technical riders for the upcoming season?\n\nBest regards,",
    "notes": "Top preschool draw in the GCC region with high merchandise demand."
  },
  {
    "id": "IP-036",
    "title": "Miraculous Ladybug Live: The Musical Show",
    "category": "High-Flying Superhero Theatrical Musical",
    "licensor": "Miraculous Corp (ZAG & Mediawan)",
    "producer": "Proactiv Entertainment / EventBox",
    "person": "Nicolas Atlan (President, Miraculous Corp) / Nicolas Renna (CEO, Proactiv)",
    "website": "https://www.miraculous.to",
    "email": "live@miraculous.to / info@proactiv.es",
    "social": "linkedin.com/company/zag-entertainment | @miraculous",
    "past_shows": "European and Latin American arena/theater tours (Madrid, Paris, Buenos Aires), 100K+ attendees",
    "venue_fit": "QNCC Auditorium or Lusail Multipurpose Arena; features aerial acrobatic stunts, LED screens, and pop songs",
    "status": "Not Contacted",
    "email_template": "Subject: Tour Booking Proposal: Miraculous Ladybug Live Musical in Doha\n\nDear Miraculous Corp & Proactiv Entertainment Teams,\n\nI am reaching out regarding hosting Miraculous Ladybug Live: The Musical Show in Doha, Qatar. Our Doha-based entertainment operations organization specializes in large-scale family productions and superhero brand activations. With Miraculous Ladybug enjoying massive cross-demographic popularity among kids aged 6-14 in the Gulf, staging the live production at QNCC would be a standout seasonal event. We would be pleased to evaluate your international touring schedule, spatial rigging requirements, and licensing terms.\n\nBest regards,",
    "notes": "Strong girl-empowerment superhero theme with high aerial rigging requirements."
  },
  {
    "id": "IP-037",
    "title": "Sonic Symphony & Sonic Live in Concert World Tour",
    "category": "Video Game Symphony & Rock Concert Spectacle",
    "licensor": "SEGA",
    "producer": "SOHO Live / Games Press Touring",
    "person": "Ivo Gerscovich (SVP Chief Business & Brand Officer, SEGA) / Alex El-Nemer (CEO, SOHO Live)",
    "website": "https://www.sonicsymphony.com",
    "email": "contact@soho-live.com / sonic@sega.com",
    "social": "linkedin.com/company/sega | @sonicthehedgehog",
    "past_shows": "Sold-out global tours across London (Barbican), Los Angeles, Paris, Tokyo, and Sydney (30+ global stops)",
    "venue_fit": "Qatar National Convention Centre (QNCC) Auditorium; combines live symphony orchestra, rock band, and synchronized gaming visuals",
    "status": "Not Contacted",
    "email_template": "Subject: Concert Booking Inquiry: Sonic Symphony World Tour in Doha, Qatar\n\nDear SEGA & SOHO Live Touring Teams,\n\nI am writing to propose hosting the Sonic Symphony World Tour in Doha, Qatar, at the Qatar National Convention Centre (QNCC) Auditorium. Doha has a vibrant gaming community and an active concert scene, making this fusion of orchestral score, rock band performance, and gaming nostalgia an ideal headliner. Our production group coordinates premier live music events and venue logistics in Qatar. Please let us know who we can connect with to evaluate promoter terms and routing windows for 2026/2027.\n\nBest regards,",
    "notes": "Excellent demographic crossover from teenagers to nostalgic adults."
  },
  {
    "id": "IP-038",
    "title": "Pokémon: Fossil Museum & Pop-Up Plaza",
    "category": "Interactive STEM Museum Exhibition & Pop-Up Game Zone",
    "licensor": "The Pokémon Company International",
    "producer": "The Pokémon Company / Field Museum Touring",
    "person": "Colin Palmer (VP of Marketing, The Pokémon Company) / Megan Malvern (Director of Touring)",
    "website": "https://www.pokemon.com",
    "email": "bizdev@pokemon.com / exhibitions@fieldmuseum.org",
    "social": "linkedin.com/company/the-pokemon-company-international | @pokemon",
    "past_shows": "National Museum of Nature and Science Tokyo, Field Museum Chicago, global pop-up arenas",
    "venue_fit": "DECC or Katara Cultural Village; combines real-world paleontology fossils with Pokémon counterparts and interactive discovery labs",
    "status": "Not Contacted",
    "email_template": "Subject: Host Venue Proposal: Pokémon Experiential Exhibition in Doha, Qatar\n\nDear The Pokémon Company International Partnerships Team,\n\nI am contacting you regarding bringing a Pokémon experiential exhibition (such as the Pokémon Fossil Museum or an interactive Trading Card Game Pocket Plaza) to Doha, Qatar. Our event management team coordinates premier museum and commercial activations in Doha, working closely with DECC and Katara. Given the immense cultural footprint of Pokémon across the Middle East, an official exhibition would be a benchmark cultural tourism attraction. We would welcome an introductory meeting to discuss spatial requirements and potential residency dates.\n\nBest regards,",
    "notes": "Extremely high merchandise and viral foot-traffic generation."
  },
  {
    "id": "IP-039",
    "title": "Dora the Explorer: Dora's Pirate Adventure",
    "category": "Live Theatrical Musical & Interactive Stage Quest",
    "licensor": "Paramount Global / Nickelodeon",
    "producer": "Life Like Touring / EventBox",
    "person": "Pam Kaufman (President, Paramount Consumer Products) / Anton Berezin (Life Like Touring)",
    "website": "https://www.nickjr.com",
    "email": "lbe@paramount.com / info@eventboxonline.com",
    "social": "linkedin.com/company/paramount | @nickjr",
    "past_shows": "Toured over 20 countries, including Australia, UK, South Africa, and Middle East dates; over 3M global attendees",
    "venue_fit": "QNCC Theater or Katara Opera House; bilingual edutainment stage show with strong call-and-response audience participation",
    "status": "Not Contacted",
    "email_template": "Subject: Touring Availability: Dora the Explorer Live Production in Doha\n\nDear Paramount Live Experiences & Life Like Touring Teams,\n\nI am writing to inquire about international routing dates for Dora the Explorer: Dora's Pirate Adventure in Doha, Qatar. Our event production company specializes in family theatrical presentations in Doha, providing end-to-end venue coordination at the QNCC Theater. Dora the Explorer remains a cornerstone educational brand with broad bilingual appeal. We would be pleased to receive your technical package, touring logistics specifications, and commercial promoter terms.\n\nBest regards,",
    "notes": "Bilingual (English/Arabic/Spanish) integration potential."
  },
  {
    "id": "IP-040",
    "title": "Care Bears: Unlock the Magic Live & Pop-Up",
    "category": "Theatrical Stage Show & Themed Interactive Cafe Pop-Up",
    "licensor": "Cloudco Entertainment",
    "producer": "Cloudco Experiential / Live Nation Kids",
    "person": "Ian Lambur (EVP Content & Commercial Strategy, Cloudco) / Robert Prinzo (Head of Global Licensing)",
    "website": "https://www.cloudcoentertainment.com",
    "email": "licensing@cloudcoentertainment.com / info@cloudcoentertainment.com",
    "social": "linkedin.com/company/cloudco-entertainment | @carebears",
    "past_shows": "UK touring stage musical, Asia Pacific pop-up cafes (Singapore, Seoul), experiential retail activations",
    "venue_fit": "Place Vendôme or Mall of Qatar Atrium; colorful, optimistic aesthetic with immersive photo stations and character meet-and-greets",
    "status": "Not Contacted",
    "email_template": "Subject: Experiential Collaboration: Care Bears Pop-Up & Live Show in Qatar\n\nDear Cloudco Entertainment Partnerships Team,\n\nI am reaching out regarding hosting a Care Bears interactive experiential pop-up or live character stage performance in Doha, Qatar. Our organization manages high-end retail activations and family entertainment across Doha's leading luxury malls, including Place Vendôme and Mall of Qatar. The Care Bears' vibrant and wholesome aesthetic offers outstanding dwell-time and merchandising synergy. We would welcome a conversation regarding licensing options and available activation formats for the upcoming season.\n\nBest regards,",
    "notes": "Ideal for retail mall atriums and seasonal photo installations."
  },
  {
    "id": "IP-041",
    "title": "Play-Doh Imagination Center & Wonder Park",
    "category": "Active Sensory Play FEC & Hands-On Creative Zone",
    "licensor": "Hasbro Global Location Based Entertainment",
    "producer": "Kingsmen Creatives / Hasbro LBE",
    "person": "Matt Proulx (VP Global LBE, Hasbro) / Andrew Cheng (Group CEO, Kingsmen)",
    "website": "https://www.kingsmen-int.com",
    "email": "lbe@hasbro.com / info@kingsmen-int.com",
    "social": "linkedin.com/company/hasbro | @playdoh",
    "past_shows": "Permanent and pop-up locations in Singapore, Manila, and US touring sensory zones",
    "venue_fit": "Doha Festival City or Mall of Qatar; modular indoor FEC concept with sensory play tables, giant sculpting zones, and digital coloring",
    "status": "Not Contacted",
    "email_template": "Subject: LBE Franchise Inquiry: Play-Doh Imagination Center in Doha, Qatar\n\nDear Hasbro LBE & Kingsmen Creatives Teams,\n\nI am writing to express interest in developing a Play-Doh Imagination Center or touring sensory wonder park in Doha, Qatar. Our event and entertainment development company works closely with premier commercial developers in Qatar seeking high-dwell-time, educational family attractions. Play-Doh's sensory, screen-free tactile creativity aligns perfectly with regional parenting priorities. Could we arrange an exploratory meeting with your location-based entertainment team to discuss franchise or hosting models?\n\nBest regards,",
    "notes": "Exceptional screen-free sensory play concept for younger children."
  },
  {
    "id": "IP-042",
    "title": "Geronimo Stilton Live in the Kingdom of Fantasy",
    "category": "Spectacular Family Musical & Fantasy Adventure",
    "licensor": "Atlantyca Entertainment",
    "producer": "Spanish Theatricals / Focus Entertainment",
    "person": "Marco Piccinini (Licensing Manager, Atlantyca) / Claudia Mazzucco (CEO, Atlantyca)",
    "website": "https://www.atlantyca.com",
    "email": "licensing@atlantyca.com / info@atlantyca.com",
    "social": "linkedin.com/company/atlantyca-entertainment | @geronimo_stilton_official",
    "past_shows": "Toured over 15 countries across Europe (Spain, Italy, Belgium, Switzerland) and North America, 500K+ tickets sold",
    "venue_fit": "QNCC Auditorium or Katara Drama Theater; Broadway-style fantasy sets, holographic projections, and original music",
    "status": "Not Contacted",
    "email_template": "Subject: Theatrical Host Inquiry: Geronimo Stilton Live Musical in Doha\n\nDear Atlantyca Entertainment Live Team,\n\nI am writing to explore host promoter booking opportunities for Geronimo Stilton Live in the Kingdom of Fantasy in Doha, Qatar. Our event production group manages family theater seasons in Doha, providing complete technical support at premier venues such as the QNCC Auditorium. Geronimo Stilton is widely read across international schools in Qatar and the GCC. We would be delighted to discuss touring package availability, freight logistics, and promoter co-production terms.\n\nBest regards,",
    "notes": "Strong school reading campaign tie-in."
  },
  {
    "id": "IP-043",
    "title": "Wallace & Gromit: A Grand Day Out & Inflatable Inventions",
    "category": "Interactive Inflatable Obstacle Park & Claymation Pop-Up",
    "licensor": "Aardman Animations",
    "producer": "Aardman Live Experiences",
    "person": "Ngaio Harding-Hill (Head of Attractions, Aardman) / Sean Clarke (Managing Director)",
    "website": "https://www.aardman.com",
    "email": "live@aardman.com / licensing@aardman.com",
    "social": "linkedin.com/company/aardman-animations | @wallaceandgromitofficial",
    "past_shows": "V&A London exhibition, touring workshops and outdoor contraption obstacle challenges across the UK, Australia, and Japan",
    "venue_fit": "Aspire Zone outdoor park, Lusail Boulevard, or DECC; combines modular inflatable wacky inventions with claymation model-making workshops",
    "status": "Not Contacted",
    "email_template": "Subject: Experiential Partnership: Wallace & Gromit Interactive Activation in Qatar\n\nDear Aardman Live Experiences Team,\n\nI am contacting you regarding developing an official Wallace & Gromit interactive activation or inflatable inventions play park in Doha, Qatar. Our event production company has substantial experience coordinating large-scale inflatable courses and family workshops in Qatar. Wallace & Gromit's inventive British humor and hands-on clay animation workshops would offer a truly distinctive attraction for Qatar's seasonal event calendar. We would love to discuss licensing parameters and modular asset availability.\n\nBest regards,",
    "notes": "Blends active physical play with creative clay modeling workshops."
  },
  {
    "id": "IP-044",
    "title": "Gigantosaurus: Dino Discovery Live!",
    "category": "Prehistoric Dinosaur Puppet Musical & Explorer Quest",
    "licensor": "Cyber Group Studios",
    "producer": "Out of the Box Productions / Cyber Group Live",
    "person": "Raphaëlle Mathieu (COO, Cyber Group Studios) / Bruno Maquart (VP Licensing)",
    "website": "https://www.cybergroupstudios.com",
    "email": "licensing@cybergroupstudios.com / contact@cybergroupstudios.com",
    "social": "linkedin.com/company/cyber-group-studios | @gigantosaurus_official",
    "past_shows": "Touring theaters across North America and Europe, live museum dinosaur discovery tie-ins",
    "venue_fit": "QNCC Theater or Katara Cultural Village; features giant puppetry dinosaurs, educational palaeo-facts, and catchy music",
    "status": "Not Contacted",
    "email_template": "Subject: Tour Booking Inquiry: Gigantosaurus Live Musical in Doha, Qatar\n\nDear Cyber Group Studios Live Experiences Team,\n\nI am writing to inquire about international touring availability for Gigantosaurus: Dino Discovery Live! in Doha, Qatar. Dinosaur-themed family entertainment achieves consistently high ticket sales across the Gulf. Our event production company in Doha delivers turnkey theatrical staging and local marketing at premier facilities including the QNCC Theater. Could you provide details regarding your touring requirements, technical riders, and Middle East routing windows for the upcoming season?\n\nBest regards,",
    "notes": "Combines dinosaur fascination with preschool adventure."
  }
];

// Helper to get stored IPs or initialize
function getStoredIPs() {
  try {
    const raw = localStorage.getItem('doha_ip_leads');
    if (raw) {
      const parsed = JSON.parse(raw);
      if (Array.isArray(parsed) && parsed.length > 0) {
        return parsed;
      }
    }
  } catch (e) {
    console.warn('Failed reading from localStorage', e);
  }
  return JSON.parse(JSON.stringify(INITIAL_IPS));
}

// Helper to save IPs
function saveStoredIPs(ips) {
  try {
    localStorage.setItem('doha_ip_leads', JSON.stringify(ips));
  } catch (e) {
    console.warn('Failed saving to localStorage', e);
  }
}

// Reset to factory defaults
function resetStoredIPs() {
  localStorage.removeItem('doha_ip_leads');
  return JSON.parse(JSON.stringify(INITIAL_IPS));
}
